---
title: "Preprocessing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
australianWeather <- read.csv(file = 'weatherAUS.csv')
```


```{r}
library(naniar)
library(ggplot2)
library(reshape2)

nums <- unlist(lapply(australianWeather, is.numeric))  

corMat=cor(australianWeather[,nums], method = c("pearson"),use = "complete.obs")


melted_corMat <- melt(corMat)

ggplot(data = melted_corMat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()

gg_miss_var(australianWeather,show_pct = TRUE) + labs(y = "Percentage of Missing values")
```

We remove the columns with over 30% NAs and transform Date into Season
```{r}
library(zoo)
  
yq <- as.yearqtr(as.yearmon(australianWeather$Date, "%Y-%m-%d") + 1/12)
australianWeather$Season <- factor(format(yq, "%q"), levels = 1:4, 
                labels = c("winter", "spring", "summer", "fall"))

australianWeather <- subset (australianWeather, select = -Date)

summary(australianWeather)

australianWeather <- subset (australianWeather, select = -c(Evaporation,Sunshine,Cloud3pm,Cloud9am))

trainIndex <- createDataPartition(australianWeather$RainTomorrow, p = .8, 
                                  list = FALSE, 
                                  times = 1)
australianWeatherTrain <- australianWeather[ trainIndex,]
australianWeatherTest  <- australianWeather[-trainIndex,]


```
We use MICE to apply predictive mean matching to fill our numeric NAs, drop the NAs in non-numeric columns, and scale the dataset
```{r}

library(mice)
library(tidyr)
library(caret)
set.seed(1)

imputed_Data <- mice(australianWeatherTrain, m=1, maxit = 50, method = 'pmm', seed = 500)

australianWeatherNoNA=complete(imputed_Data,1)

australianWeatherNoNA=drop_na(australianWeatherNoNA)

gg_miss_var(australianWeatherNoNA,show_pct = TRUE) + labs(y = "Percentage of Missing values")


scaled <- lapply(australianWeatherNoNA, function(x) if(is.numeric(x)){
                     scale(x, center=TRUE, scale=TRUE)
                      } else x)
scaled=as.data.frame(scaled)
```


```{r}
summary(scaled)

g1 <- ggplot(scaled, aes(x = Season)) +
  geom_bar(alpha = 0.7) + theme_bw() +
  theme(legend.position="bottom")

g2 <- ggplot(scaled, aes(x = WindGustDir)) +
  geom_bar(alpha = 0.7) + theme_bw() +
  theme(legend.position="bottom")
g3 <- ggplot(scaled, aes(x = WindDir9am)) +
  geom_bar(alpha = 0.7) + theme_bw() +
  theme(legend.position="bottom")
g4 <- ggplot(scaled, aes(x = WindDir3pm)) +
  geom_bar(alpha = 0.7) + theme_bw() +
  theme(legend.position="bottom")
g5 <- ggplot(scaled, aes(x = RainToday)) +
  geom_bar(alpha = 0.7) + theme_bw() +
  theme(legend.position="bottom")
g6 <- ggplot(scaled, aes(x = RainTomorrow)) +
  geom_bar(alpha = 0.7) + theme_bw() +
  theme(legend.position="bottom")


g7 <- ggplot(scaled, aes(x = MinTemp)) +
  geom_density(alpha = 0.7) + theme_bw() +
  theme(legend.position="none")
g8 <- ggplot(scaled, aes(x = MaxTemp)) +
  geom_density(alpha = 0.7) + theme_bw() +
  theme(legend.position="none")
g9 <- ggplot(scaled, aes(x = Rainfall)) +
  geom_density(alpha = 0.7) + theme_bw() +
  theme(legend.position ="none" )
g10 <- ggplot(scaled, aes(x = WindSpeed9am)) +
  geom_density(alpha = 0.7) + theme_bw() +
  theme(legend.position ="none" )
g11 <- ggplot(scaled, aes(x = WindSpeed3pm)) +
  geom_density(alpha = 0.7) + theme_bw() +
  theme(legend.position ="none" )
g12 <- ggplot(scaled, aes(x = Humidity9am)) +
  geom_density(alpha = 0.7) + theme_bw() +
  theme(legend.position ="none" )
g13 <- ggplot(scaled, aes(x = Humidity3pm)) +
  geom_density(alpha = 0.7) + theme_bw() +
  theme(legend.position ="none" )
g14 <- ggplot(scaled, aes(x = Temp9am)) +
  geom_density(alpha = 0.7) + theme_bw() +
  theme(legend.position ="none" )
g15 <- ggplot(scaled, aes(x = Temp3pm)) +
  geom_density(alpha = 0.7) + theme_bw() +
  theme(legend.position ="none" )


grid.arrange(arrangeGrob(g1 + theme(legend.position="none"), g2 + theme(legend.position="none"),
g3 + theme(legend.position="none"),g4 + theme(legend.position="none"), g5 + theme(legend.position="none"), g6 + theme(legend.position="none"), g7 + theme(legend.position="none"), g8 + theme(legend.position="none"), g9 + theme(legend.position="none"), g10 + theme(legend.position="none"), g11 + theme(legend.position="none"), g12 + theme(legend.position="none"), g13 + theme(legend.position="none"), g14 + theme(legend.position="none"), g15 + theme(legend.position="none"),nrow=4),heights=c(10, 1))

```


```{r}
preprocessedTrain=scaled[trainIndex]
preprocessedTest=scaled[-trainIndex]
```